### ISSUE TITLE
Different errors

### ISSUE THREAD

**Issue by hikyle** [sirdoombox/Overwatch.Net#1]
When I try running
`OverwatchPlayer player = new OverwatchPlayer("kyle#12341", Region.US);`
`await player.UpdateStats();`
` Console.WriteLine(player.Stats.AllHeroes.Best.DamageDoneMostinGame)`

I get: Additional information: OverwatchPlayer's Battletag is not valid - Format is 'User#1234`

So I try manually replacing the # with a - and it appears to work until it hits player.UpdateStats() and i get the message "Value cannot be null."

**Comment by sirdoombox** [comment]
Ah that's my fault, an absolutely vast oversight, I've just fixed and pushed it here and a new version up to Nuget.

Thanks for that, I can't believe I missed it.
