### ISSUE TITLE
Player.Platform always returns PC

### ISSUE THREAD

**Issue by Giggitybyte** [sirdoombox/Overwatch.Net#10]
`Player.Platform` always returns PC, even for console players.

Very simple to reproduce: 

1. Create a new client
2. Try to get a console player (Example: XBL `zSuperSaiyanGod`, PSN `boomboom2k`)
3. Check the platform

**Comment by sirdoombox** [comment]
My bad, missed an assignment out, applied a quick bandaid to the problem and should work as expected.
New version being pushed out as we speak.

Thanks for the heads up!

**Comment by Giggitybyte** [comment]
Thank you!
