### ISSUE TITLE
Player lookup will throw if the profile for the user is private.

### ISSUE THREAD

**Issue by Giggitybyte** [sirdoombox/Overwatch.Net#11]
A `NullReferenceException` will be [thrown](https://x0.at/O0X.png) when attempting to look up a player with a private profile.
A new testable exception would be nice to have for when this occurs.

**Comment by sirdoombox** [comment]
Fixed, now it will handle private profiles, scraping whatever data is available and ignoring the rest.

To check if a profile is private you can just use `Player.IsProfilePrivate`.

Stats won't be available but basic profile information will be.
