### ISSUE TITLE
Require PhantomJS & Selenium to fully parse data that is loaded in from other sources.

### ISSUE THREAD

**Issue by sirdoombox** [sirdoombox/Overwatch.Net#15]
It's not difficult to do, but the extra dependencies could be a problem so I'm putting this up here just in case someone specifically has an issue with that, otherwise I'll steam ahead and add those dependencies to the project.

This could noticeably slow down pageloads and therefore act to damage the performance of people who make a lot of requests all, for data that you may not want or need. I'll do my best to make it optional whilst highlighting data (via XAML docs) that is dependent on using the new libs so you can make a decision for yourself.

**Comment by sirdoombox** [comment]
It seems like PhantomJS has been deprecated, so I'm not quite sure how to go about executing the page fully to grab all the data.

Any help would be appreciated.

**Comment by sirdoombox** [comment]
Found a decent way around one or two pieces of data by grabbing values and making separate XHR requests.

**Comment by Giggitybyte** [comment]
I realize you've closed this already, but I'd like to put my two cents in.

I'm all for more data and I don't mind extra dependencies (what's a few more, right?), but I do mind when performance suffers. It's one of the nice things about your library; it's very fast. 
If you do ever implement something that would considerably reduce performance, it'd be nice if we had a way to choose between more data with slow page loads and less data with faster page loads. Perhaps separate methods or an additional parameter for existing methods.

**Comment by sirdoombox** [comment]
Yep that's the plan, I'm adding an extra method for discovering other profiles attached to a user, lucked out and the blizzard player ID is used as an argument in a JS script inside the HTML so I can make a separate request using that number to find any other profiles associated with that player.

From there you can grab all the other profiles if you like with yet another method. The only additional dependency is Newtonsoft.Json at this point, and I'm alright with that.
