### ISSUE TITLE
Endorsements return non-whole numbers. 

### ISSUE THREAD

**Issue by Giggitybyte** [sirdoombox/Overwatch.Net#16]
Another pesky Blizzard change for you to try to sort out.

Up until about yesterday endorsements would return [whole numbers](https://x0.at/YTT.png) for each type of endorsement. Today, however, they return [numbers](https://x0.at/aN7.png) below one. I believe these numbers are percentages because when they're added up, they always add up to [one](https://x0.at/mBN.png).

**Comment by sirdoombox** [comment]
Job's done, change is live, should make it a bit easier to deal with.
Used decimal for increased precision because it seems like you might want to be precise with this.

**Comment by Giggitybyte** [comment]
Man, I've got to thank you for being so responsive to this project. Keep it up <3

Really does suck that Blizzard no longer displays the exact number of endorsements. I'll miss that.
