### ISSUE TITLE
The problem of the data of the never-played heroes.

### ISSUE THREAD

**Issue by BadAssKoala** [sirdoombox/Overwatch.Net#4]
If the user has never played some hero, then, the drop-down list for selecting hero on the playoverwatch stat page does not contain the item of the hero not played.

the method, PlayerStats.UpdateStatsFromPage, uses that list and omits the stats of the hero.
So the stats group object of the hero remain NULL and cannot access to the stats group.
It would be the obstacle when using the stats generally.

**Comment by sirdoombox** [comment]
I agree somewhat with your argument, I shall attempt to ammend the code so that those objects are all instanced regardless of whether or not they have been played.

**Comment by sirdoombox** [comment]
Implemented, no more null objects - Pushing to Github and Nuget as we speak.
