### ISSUE TITLE
Sombra Stats

### ISSUE THREAD

**Issue by wyattpaq14** [sirdoombox/Overwatch.Net#7]
Doesn't display stats for the new hero 'Sombra'. Not entirely sure if this is just user error, or if there is an actual problem with this API.
![untitled](https://cloud.githubusercontent.com/assets/21962099/23388461/5690d4c4-fd30-11e6-8515-54b36a2e0b0e.png)

**Comment by sirdoombox** [comment]
As far as I can tell this appears to be an issue on your end, Sombra appears in your profile data for me.

![devenv_2017-02-28_08-05-26](https://cloud.githubusercontent.com/assets/7238201/23396689/dd6f0b44-fd8c-11e6-8419-877f049f6460.png)

If you could show me your code I may be able to see why you're unable to retrieve the stats from your profile for Sombra.

**Comment by wyattpaq14** [comment]
Thanks for getting back to me, turns out the hero I was trying to search didn't event have "Hero Specific" stats on their playoverwatch profile. Looks like it works now.
![ss](https://cloud.githubusercontent.com/assets/21962099/23412402/63a4385e-fda3-11e6-8931-8b950275f321.png)

**Comment by sirdoombox** [comment]
Alright, glad you fixed your issue!
